[package]
name = "ssc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
clap_derive = "4.5.5"
env_logger = "0.11.3"
log = "0.4.21"
zeroconf = "0.14.1"
